[helpers]

[default]
depends = []

[default.files]
alacritty = "~/.config/alacritty"
hypr = "~/.config/hypr"
rofi = "~/.config/rofi"
starship = "~/.config"
swaylock = "~/.config/swaylock"
swww = "~/.config/swww"
themes = "~/.themes"
tmux = "~/.config/tmux"
waybar = "~/.config/waybar"
zsh = "~"
nvim = "~/.config/nvim"

[default.variables]
